version: '3'
services:
  java-srv:
    build:
      context: java-srv
    ports:
      - "80:8080"
    depends_on:
      - db
    links:
      - "db:db"

  db:
    build:
      context: db
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=maria
      - COUCHDB_PASSWORD=pass
    volumes:
      - ./java-srv/log:/root/log
